version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../src:/app/src
      - ../scripts:/app/scripts
    environment:
      - PYTHONUNBUFFERED=1